Several correctness, readability, consistency issues addressed

diff --git a/.local/bin/git-sweep b/.local/bin/git-sweep
--- a/.local/bin/git-sweep
+++ b/.local/bin/git-sweep
@@ -1,26 +1,26 @@
 #!/bin/zsh
 
-REQUIRED_VERSION=5.3
+local required_version=5.3
 type is-at-least > /dev/null 2>&1 || autoload -Uz is-at-least
-if ! is-at-least $REQUIRED_VERSION; then
-  echo "Requires Zsh $REQUIRED_VERSION or newer"
+if ! is-at-least $required_version; then
+  echo "Requires Zsh $required_version or newer"
   exit 1
 fi
 
-getopts 'd' opt && DELETE=1
-
-if [[ -v "$DELETE" ]]; then
+getopts 'd' opt && local delete=1
+if [[ -v "$delete" ]]; then
   echo 'Deleting stale branches'
 else
   echo 'Listing stale branches (delete with -d)'
 fi
 
-for branch in $(git branch | tr -d ' '| grep -v '^*' | grep -v 'master'); do
-  older_commits="$(git reflog show -1 --exclude=master --before='4 weeks ago' $branch)"
-  newer_commits="$(git reflog show -1 --exclude=master --after='4 weeks ago' $branch)"
+local expiration_date='4 weeks ago'
+for branch in $(git branch | tr -d ' ' | grep -v '^*' | grep -v 'master'); do
+  local older_commits="$(git reflog show -1 --format=oneline --until=$expiration_date $branch)"
+  local newer_commits="$(git reflog show -1 --format=oneline --since=$expiration_date $branch)"
 
-  if [[ -n $older_commits && -z $newer_commits ]]; then
-    if [[ -v "$DELETE" ]]; then
+  if [[ -n "$older_commits" && -z "$newer_commits" ]]; then
+    if [[ -v "$delete" ]]; then
       git branch -D $branch
     else
       echo "Found branch with stale commits: $branch"
